builds:
  - goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
nfpms:
  - maintainer: ZERM Team <zerm@chrissx.de>
    description: The current ZERM backend
    homepage: https://github.com/ZERMZeitung/jasmin
    license: MPLv2
    formats:
      - deb
      - rpm
      - apk
